theme.yamal fixes, typo fixes, re did shop page using flexboxes, …
lemonstand/lscloud-theme-coffree pull request #17
Opened 2017-02-17 00:22 UTC by Mopok

fixed featured items on home page. This is first 10 or so checkboxes on Ross's fix list seen here:
https://github.com/lemonstand/lemonstand-2/issues/3760

2017-02-17 00:48 UTC, tomcornall requested changes
@Mopok All very minor feedback, looks good.

- [x] Need screenshot of Pagination after centering.

2017-02-17 00:48 UTC, tomcornall commented on pages/registered/page-registered.htm
>  	<h4 class="buffer">Continue Shopping or Shop our featured collection</h4>
Could be useful to link to the "/shop", like this:

`<h4 class="buffer"><a href="/shop">Continue Shopping</a> or Shop from our featured collection</h4>`

2017-02-17 00:48 UTC, tomcornall commented on partials/home-featured-products.htm
> +	{% else %}
👍  Good fallback here

2017-02-17 00:48 UTC, tomcornall commented on partials/shop-product-loop.htm
>  {% set shop_item = theme.shopItemsPerPage %}
Can probably remove this first set of `shop_item`, it's getting overwritten in the next line anyways.

2017-02-17 00:48 UTC, tomcornall commented on theme.yaml
> +    featuredSubscriptions: { type: text, title: 'Name of your featured subscription plans', default: featuredPlans }
Should be something like:

"Name of your subscription product collection"

2017-02-17 00:48 UTC, tomcornall commented on resources/css/combined.css
> +
extra line

2017-02-17 00:48 UTC, tomcornall commented on resources/css/combined.css
> +	padding-top:50px;
Needs a space between the colon and the value

2017-02-17 00:48 UTC, tomcornall commented on resources/css/combined.css
> +
Some weird spacing in this .jumbotron class (realize a lot of this was already here): should remove extra lines, and needs space between colons and values

2017-02-17 00:48 UTC, tomcornall commented on resources/css/combined.css
>  	font-weight:400;
another space needed, b/w colon and value

2017-02-17 19:21 UTC, Mopok commented
Showed centred pagination
![screen shot 2017-02-17 at 10 45 15 am](https://cloud.githubusercontent.com/assets/14959054/23079784/3d85abce-f503-11e6-992f-5ac14b0df432.png)

2017-02-20 21:15 UTC, tomcornall approved these changes

2017-02-20 21:16 UTC, merged