3760 checkout fixes
lemonstand/lscloud-theme-coffree pull request #23
Opened 2017-02-23 19:23 UTC by Mopok

Do #22  first.

Product checkout fixes

2017-02-23 20:21 UTC, tomcornall requested changes
@Mopok Some questions, and a reminder to fix the total label

2017-02-23 20:21 UTC, tomcornall commented on partials/shop-invoicetotals.htm
>      <li class="list-group-item">Item Total: <div class="pull-right">{{ cartTotalNoTax|currency }}</div></li>
Reminder for the total here, should say only "Total:" (if it is not an item total)

2017-02-23 20:21 UTC, tomcornall commented on pages/checkout-start/page-checkout-start.htm
> -                </form>
No more guest checkout - is this desired?

2017-02-23 20:21 UTC, tomcornall commented on partials/shop-cart-totals.htm
> -</div>
The cart totals are directly in the cart page now? That's ok if so, just want to be sure this partial was meant to be deleted.

2017-02-23 20:21 UTC, tomcornall commented on partials/shop-invoicetotals.htm
> +<li class="list-group-item">Tax:<div class="pull-right">{{ invoice.tax_total|currency }}</div></li>
🌮

2017-02-23 20:25 UTC, Mopok commented on partials/shop-cart-totals.htm
> -</div>
They now use the same partial from the checkout. Because they use the same variables.

2017-02-23 20:29 UTC, tomcornall commented on partials/shop-cart-totals.htm
> -</div>
👍

2017-02-27 19:52 UTC, tomcornall approved these changes

2017-02-27 19:52 UTC, merged